server:
    port : 80
configuration:
    projectName : Spring Boot
    someOtherKey : Some Other Value
    myIp : 172.30.1.50
    some_crap : Nonsense
    servers: 
        - 172.30.1.50
        - 172.30.0.99
        - 172.30.2.59
